"""empty message

Revision ID: 1420aa8a1292
Revises: 26f1d430aded
Create Date: 2015-12-08 16:39:38.669679

"""

# revision identifiers, used by Alembic.
revision = '1420aa8a1292'
down_revision = '26f1d430aded'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('group', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_books')
    ### end Alembic commands ###
